name: Build OpenWrt Package

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-openwrt-package-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Package
    uses: ./.github/workflows/build-core.yml
    with:
      openwrt_version: '25.12.3'
      openwrt_target: 'qualcommax/ipq807x'
      openwrt_arch: 'aarch64_cortex-a53'
      package_name: 'luci-app-internet-led'
      package_ext: 'apk'
      upload_artifact: true
